# Generated by Django 3.1.7 on 2021-02-21 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collecteddata',
            name='user',
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='first_name',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='last_name',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='providers',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
